#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y nginx
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

sudo service nginx start
