#!/usr/bin/env bash
# Configure nginx server that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get install -y nginx

sudo echo "Hello World!" | sudo tee /var/www/html/index.html
string_rep="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGU1wu4 permanent;"
sudo sed -i "s/server_name _;/$string_rep/" /etc/nginx/sites-enabled/default


sudo service nginx restart