#!/usr/bin/env bash
# Install and configure the load balancer HAproxy on lb-01 server
# so that it send traffic to web-01 and web-02
# distribute request using roundrobin algorithm
#HAproxy should be managed via init script


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

#config file
config_server=\
"
frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 141488-web-01 54.236.28.162:80 check
        server 141488-web-02 100.26.228.145:80 check
"
echo "$config_server" | sudo tee -a /etc/haproxy/haproxy.cfg

# manage haproxy by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
